### ISSUE TITLE
[Bug]: CRITICAL FAILURE SkyrimPatcher ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Kiyozz** [Monitor221hz/Pandora-Behaviour-Engine-Plus#198]
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v1.4.1-alpha

### Provide Instructions on Reproducing the Problem

v1.3.0-alpha was OK.

You can install all the mods in ActiveMods.txt (in the files.zip). I don't know which mods can cause the error.

I would like to use 1.4 for the kill move fix, but... critical failure!

### Provide Relevant Files

Relevant files are in [files.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/15051673/files.zip) (Engine.log and ActiveMods.txt)

Log says 1.3.0-alpha BTW, but I'm using 1.4.1-alpha

### Provide Visual Proof (optional)

<img width="543" alt="image" src="https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/12450333/f1aecebe-c61e-499c-90fe-c304ff1b3d04">

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment]
@Kiyozz Check v1.4.2 please, issue should be resolved

**Comment by Kiyozz** [comment]
Hey, thanks for your release. Unfortunately, the issue persist.

New Engine.log
[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/15053119/Engine.log)

**Comment by Kiyozz** [comment]
This is a Engine.log when using 1.3.0

[1.3.0-Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/15053132/Engine.log)

**Comment by Monitor144hz** [comment]
@Kiyozz is this issue fixed in the latest version?

**Comment by Monitor144hz** [comment]
Sounds good, please close the issue when you have confirmed no more problem exists. No rush!
